### ISSUE TITLE
Gestire connettori con più fonti dati

### ISSUE THREAD

**Issue by Magicianred** [noiopen/io-sdk#15]
Prevedere la possibilità, per i connettori, di scegliere tra più fonti dati

Schema (nello schema è già prevista la selezione del connettore, ma questa issue non la gestisce):
https://aws1.discourse-cdn.com/free1/uploads/noiopen/optimized/1X/95f830b788491a6e06cadc6132b906f1b293c5c8_2_690x317.png

https://noiopen.discourse.group/t/brainstorming-io-sdk-next-release-0-6/409/20

**Comment by sciabarracom** [comment]
questo dipende dal singolo connettore non è rilevante per l'io-sdk.
