### ISSUE TITLE
In admin UI aggiungere opzione "Import from Url" e "Import Custom"

### ISSUE THREAD

**Issue by Magicianred** [noiopen/io-sdk#29]
nella UI “Import from URL” e “Import Custom”, cosi abbiamo il caso di chi vuole fornire un URL per prendersi i dati e chi invece vuoe usare l’editor per personalizzare un importer…

**Comment by gdorsi44** [comment]
La funzionalità già c'è ho solo sistemato la label dell'import. 
Manca solo il controllo del campo Url se viene inserito un valore sbagliato.
