### ISSUE TITLE
[Schedulatore] logica applicativa

### ISSUE THREAD

**Issue by Magicianred** [noiopen/io-sdk#8]
Aggiungere all'io-sdk una funzione di scheduler che esegua un task ogni "tot" tempo.

Aggiungere la configurazione del "cron" all'interfaccia interfaccia utente.

https://noiopen.discourse.group/t/brainstorming-io-sdk-next-release-0-6/409/3

**Comment by Magicianred** [comment]
Hint: aggiungere una immagine docker con un qualsiasi cron che legge la configurazione da redis… e fornire una interfaccia utente per scrivere le configurazioni di cron.

**Comment by Magicianred** [comment]
Hint: https://noiopen.discourse.group/t/lo-schedulatore-come-fare/499

**Comment by ghost** [comment]
Mi sono offerto volontario per la parte relativa alla REST-API per la schedulazione come suggerito nella discussione su noiopen. Quindi se lo ritenete opportuno potete assegnarmi la issue.

**Comment by ghost** [comment]
Ho creato un prototipo funzionante della API dello schedulatore, con persistenza della configurazione su un file JSON. Il tutto è corredato da un Dockerfile e Makefile per il build ed il deploy su un container docker.

Al momento si trova in un repository separato a questa url https://github.com/francescotimperi/io-sdk-scheduler
